# Setup
title:            재밌는게 최고야
url:              https://jhy6219.github.io
paginate:         5
paginate_path:    "/posts/page:num/"
baseurl:          "/jekyll"
#permalink:       pretty
permalink:        none
timezone:         Asia/Seoul
#locale : "ko-KR"
description:      ""

sass:
  sass_dir: _sass
  style: :compressed

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

  # Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: hy
  url: https://github.com/jhy6219
  email: jhy6219@gmail.com

# Custom vars
version: 3.0.0
googleads: true # true / false

github:
  repository_edit_url: "https://github.com/jhy6219/jekyll/edit/master/"

# Navbar page list
nav:
  - title: Blog
    url: /posts
  - title: Category
    url: /category
  - title: Tags
    url: /tags
#  - title: About
#    url: /about
#  - title: Azure
#    url: /category/azure

# Gems
plugins:
  - jekyll-coffeescript
  - jekyll-gist
#  - jekyll-github-metadata
  - jekyll-paginate
#  - jekyll-relative-links
#  - jekyll-optional-front-matter
#  - jekyll-readme-index
#  - jekyll-default-layout
#  - jekyll-titles-from-headings

  - jekyll-feed
  #- jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  #- jekyll-avatar
  #- jemoji
  #- jekyll-mentions
  #- jekyll-include-cache

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
